//
// Created by David on 5/6/2018.
//

#ifndef TRIANGLEMODEL_JOINTWTPDATACOLLECTOR_H
#define TRIANGLEMODEL_JOINTWTPDATACOLLECTOR_H


class JointWTPDataCollector {

};


#endif //TRIANGLEMODEL_JOINTWTPDATACOLLECTOR_H
