//
// Created by David on 5/7/2018.
//

#ifndef TRIANGLEMODEL_DIRECTTREATEDWATERTRANSFER_H
#define TRIANGLEMODEL_DIRECTTREATEDWATERTRANSFER_H


class DirectTreatedWaterTransfer {

};


#endif //TRIANGLEMODEL_DIRECTTREATEDWATERTRANSFER_H
